name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: ActualBehaviour
    attributes:
      label: What happened?
      description: Tell us what you saw?
      placeholder: Describe the issue in detail.
      value: "Describe the issue in detail."
    validations:
      required: true

  - type: textarea
    id: ToReproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behaviour
      placeholder: What steps did you take?
      value: "What steps did you take?"
    validations:
      required: true

  - type: textarea
    id: ExpectedBehaviour
    attributes:
      label: Expected behaviour
      description: Tell us what you expected to see?
      placeholder: Expected behaviour
      value: "Expected behaviour"
    validations:
      required: true

  - type: textarea
    id: device
    attributes:
      label: Device Type
      description: What Device(s) is the issue on?
      placeholder: iPhone 12, Samsung Galaxy 21, etc
      value: "iPhone 12, Samsung Galaxy 21, etc"
    validations:
      required: true

  - type: dropdown
    id: OS
    attributes:
      label: What OS are you seeing the issue on?
      multiple: true
      options:
        - MacOS
        - ChromeOS
        - Windows
        - Linux
        - Android
        - iOS
        - Unix
    validations:
      required: true


  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Samsung Internet
        - Opera
        - Internet Explorer 11
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GregEwens/sem/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
